version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: inventory
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: inventory

	inventory:
		build: .
		image: chamaconekt/inventory
		links:
		- postgres
		container_name: inventory
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- inventory
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/inventory-nginx/nginx.conf
		depends_on:
			- inventory
		ports:
			- 80:80
		volumes_from:
			- inventory

volumes:
	inventory-static-files:
		driver:local