version '2'
services:
    db-inventory:
        image: 'postgres:9.6'
        autorestart: always
        environment: 
            - POSTGRES_USER=inventory 
            - POSTGRES_PASSWORD=J5brHrAXFLQSif0K 
            - POSTGRES_DB=inventory

    lb-inventory:
        image: 'dockercloud/haproxy:latest'
        autorestart: always
        links:
            - inventory
        ports: 
            - "80:80"
        roles:
            - global


    inventory:
        image: 'chamaconektkenya/inventory:latest'
        autorestart: always
        links: 
            - postgres
        deployment_strategy: high_availability
        target_num_containers: 4






